"""Render interview answers into profile.md + config.json (pure, stdlib only).

`profile.md` is the human-readable, hand-editable judging brief the brain reads;
it mirrors the legacy `job-finder-brief.md` structure (who-this-is-for, ranked
target paths, Tier-A hard blockers, Tier-B judge-by-duties, 0-100 rubric).
`config.json` is the machine-readable settings the brain consumes (model tag,
JobSpy search params, CV path, ports, advanced-source slots).

Both are built DETERMINISTICALLY from the final answers. Optional onboarding
assistance may help the user phrase those answers before this module is called,
but these rendering functions stay pure so the test suite can exercise them.
"""

from __future__ import annotations

from dataclasses import dataclass, field

DEFAULT_DASHBOARD_PORT = 8765
OLLAMA_BASE = "http://127.0.0.1:11434"

REMOTE_PREFS = ("remote-only", "hybrid-ok", "on-site")


@dataclass
class Answers:
    self_description: str = ""
    target_paths: list[str] = field(default_factory=list)
    search_terms: list[str] = field(default_factory=list)
    country: str = ""
    city: str = ""
    extra_countries: list[str] = field(default_factory=list)
    remote_preference: str = "remote-only"
    seniority: str = ""
    work_auth: str = ""
    exclude_companies: list[str] = field(default_factory=list)
    avoid_industries: list[str] = field(default_factory=list)
    instant_no: str = ""


def _bullets(items: list[str], empty: str = "_(none given)_") -> str:
    items = [i.strip() for i in items if i and i.strip()]
    if not items:
        return empty
    return "\n".join(f"- {i}" for i in items)


def _numbered(items: list[str], empty: str = "_(none given)_") -> str:
    items = [i.strip() for i in items if i and i.strip()]
    if not items:
        return empty
    return "\n".join(f"{n}. {i}" for n, i in enumerate(items, 1))


def render_profile(a: Answers) -> str:
    """Build the profile.md markdown the brain judges against."""
    location = a.country.strip() or "_(not set)_"
    if a.city.strip():
        location = f"{a.city.strip()}, {location}"
    # Surface every searched country so the judge doesn't down-rank a job in an
    # extra country as "wrong location" — these are deliberately in scope.
    extras = [c.strip() for c in a.extra_countries if c.strip()]
    if extras:
        location = f"{location}; also searching {', '.join(extras)}"

    blockers = []
    if a.work_auth.strip():
        blockers.append(f"Work-authorization / location limit: {a.work_auth.strip()}")
    if a.remote_preference == "remote-only":
        blockers.append("On-site or hybrid roles (remote-only search).")
    for c in a.exclude_companies:
        if c.strip():
            blockers.append(f"Company to exclude: {c.strip()}")
    for ind in a.avoid_industries:
        if ind.strip():
            blockers.append(f"Industry to avoid: {ind.strip()}")
    blockers_md = _bullets(blockers, "_(no hard blockers given)_")

    seniority = a.seniority.strip() or "_(not specified)_"
    instant_no = a.instant_no.strip() or "_(none given)_"

    return f"""# Profile

> Generated by the JobScout first-run interview. This file is gitignored and
> hand-editable — edit it any time, or re-run onboarding (`2-search-jobs.command --setup`)
> to rebuild it. The brain reads this whole file to judge each job posting.

## Who this is for

{a.self_description.strip() or "_(not described)_"}

**Seniority:** {seniority}

## Target paths (rank toward these, best first)

{_numbered(a.target_paths)}

## Search terms

The queries fed to the job boards:

{_bullets(a.search_terms)}

## Location & remote preference

- **Location:** {location}
- **Remote preference:** {a.remote_preference}

## Tier-A — hard blockers (instant no; reasoning does NOT override these)

Drop these outright — the candidate genuinely cannot or will not take them:

{blockers_md}

**Instant-no, in your words:** {instant_no}

## Tier-B — judge by the actual duties (reason from the posting)

Titles lie in both directions. Read the full posting and judge by what the
person actually does day to day, not the title word. A clear poor fit scores
low; a clear good fit scores normally; anything genuinely ambiguous is a
"maybe" (worth a look) rather than a drop. Weigh seniority, real depth of the
role versus coordination-only work, and how well the duties match the target
paths above.

## Scoring rubric (0–100)

- **90–100** — tailor-made; say why, with specifics.
- **70–89** — strong fit; clear path from this experience.
- **50–69** — plausible reach; would need positioning work.
- **30–49** — weak fit; mostly transferable but not aligned.
- **0–29** — poor fit.
- **disqualified** — hits a Tier-A blocker, regardless of other fit.

Do not inflate scores. Be honest. Treat this profile as ground truth.
"""


def build_config(a: Answers, model_tag: str, cv_path: str | None,
                 ntfy: dict | None = None) -> dict:
    """Build the machine-readable config.json the brain consumes.

    `ntfy` is the optional run-notification block ({enabled, server, topic}); when
    None (the user declined) the key is omitted entirely, which the brain reads as
    notifications-off."""
    config = {
        "model": model_tag,
        "ollama_base": OLLAMA_BASE,
        "search": {
            "queries": [q.strip() for q in a.search_terms if q.strip()],
            "country": a.country.strip(),
            "city": a.city.strip(),
            "remote_preference": a.remote_preference,
            "seniority": a.seniority.strip(),
        },
        "cv_path": cv_path,
        "dashboard_port": DEFAULT_DASHBOARD_PORT,
        # Advanced source slots (Phase 5); empty by default, user-extensible.
        "extra_rss": [],
        # Additional countries/locations to search (from onboarding or hand-edited).
        "extra_jobspy_locations": [c.strip() for c in a.extra_countries if c.strip()],
    }
    if ntfy:
        config["ntfy"] = ntfy
    return config
